### ISSUE TITLE
About code and data

### ISSUE THREAD

**Issue by Crownzz** [Yibin-Lei/CSQE#1]
Dear authors,
I'm highly interested in your work titled "Corpus-Steered Query Expansion with Large Language Models"-CSQE. However, I haven't been able to locate the associated code and data yet. I would greatly appreciate it if you could release them at your earliest convenience. I'm eager to delve deeper into understanding the technical details.
Thanks.

**Comment by Yibin-Lei** [comment]
Hi @Crownzz,

Sorry for the late reply. The code is uploaded. Please feel free to ask any further questions.

Best,
Yibin

**Comment by Yibin-Lei** [comment]
Close the issue as no further action is required. Please feel free to reopen it if needed.
